### ISSUE TITLE
Stop search engines to index/show us

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/kilink#100]
AFAIK, we need to do two things:
- Serve a `robots.txt` with the following content: 

```
User-agent: *
Disallow: /
```
- Return a header in all responses with a new header: `X-Robots-Tag: noindex`

**Comment by laureanoSilva** [comment]
I think it is enough to add this tag in base.html to solve this:

<meta name="robots" content="none" />

https://developers.google.com/webmasters/control-crawl-index/docs/robots_meta_tag?hl=en-419

**Comment by matibarriento** [comment]
Can we only allow the index in Tools and About? So people can find linkode.org but not the kilinks.

**Comment by facundobatista** [comment]
My point is: how would google find the kilinks? 

I don't think it would start trying to hit linkode.org/aaaaaaaa, linkode.org/aaaaaaab, linkode.org/aaaaaaac, etc... So google probably would index the content of a kilink after finding the URL of the kilink on some public mail list or something, which is totally OK! (because somebody made the kilink public!)

Am I missing something in this analysis? I'm not a google expert at all...

**Comment by laureanoSilva** [comment]
Well, it seems that by default google indexes the site. In fact, there are already several indexed linkodes:

https://www.google.com.ar/#q=+site:linkode.org+linkode&*

Then, we should not do anything, right?

Maybe we can use `nofollow` directive, then, only the links that have been publicly shared will be indexed.

**Comment by facundobatista** [comment]
As the linkode URLs are not shown in any list of the site, the only way google could find them is through public shared ones.

So I think we're just fine!! Closing this.
