### ISSUE TITLE
Linkode fail when code have "DROP TABLE" text

### ISSUE THREAD

**Issue by matibarriento** [facundobatista/kilink#104]
Steps
1 - Create a new linkode o new version and put "DROP TABLE" in the code (text type is indiferent)
2 - Submit
3 - "ERR_EMPTY_RESPONSE" result and can't create the new linkode.

**Comment by facundobatista** [comment]
I can create new linkodes perfectly with that text:

- I go to linkode.org
- put "DROP TABLE" in the big text field
- (text type changes automatically to "sql")
- Click on "Create linkode"
- All works fine

Mind to describe better the problem?

**Comment by matibarriento** [comment]
It could be a network issue but only happen with linkode. I did create a Linkode with "DROP TABLE" outside the work network but i can't create one (or edit one with that text) inside.
I will check if it is a local network problem and come back with news

Chrome respond with this error
![2017-01-09 14_18_45-linkode org](https://cloud.githubusercontent.com/assets/5904261/21776855/4e522d02-d67b-11e6-9d20-c4e0d54a4aed.png)

And firefox respond with this.

![2017-01-09 14_18_50-problema al cargar la pagina](https://cloud.githubusercontent.com/assets/5904261/21776856/4e556f76-d67b-11e6-915e-987ef31e7b43.png)

**Comment by facundobatista** [comment]
I just created this one for you: http://linkode.org/zv9DL5QKHflDYJtYUWWom2

**Comment by matibarriento** [comment]
Yes, but when I submit a new version fail

**Comment by facundobatista** [comment]
Closing this as invalid, as this clearly is something that happens inside your workplace only. Note that #105 will surely help in this case.
