### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/kilink#113]
We should have https://linkode.org

**Comment by Abuelodelanada** [comment]
https://letsencrypt.org/ es amigable

**Comment by tomasdelvechio** [comment]
[Certbot](https://certbot.eff.org/) automatiza **mucho** del trabajo de instalar y actualizar Let's encrypt. Lo usé hace 1 semana. Esta [recomendado oficialmente](https://letsencrypt.org/docs/faq/) (Ver _Is there a Let’s Encrypt (ACME) client for my operating system?_)

**Comment by facundobatista** [comment]
It currently works with HTTPS, see https://linkode.org/ , what still needed to do is to 303 from HTTP to HTTPS

**Comment by facundobatista** [comment]
This is already done
