### ISSUE TITLE
Put a hover on nodes in the tree

### ISSUE THREAD

**Issue by facundobatista** [facundobatista/kilink#49]
The hover should say something "See this node's version"

**Comment by matibarriento** [comment]
We have the text with the version number. I think it's good enough. When there are users, we can show more info

**Comment by facundobatista** [comment]
We should include all the needed data in the basic information that comes from the server with the tree itself. 

Let's not do another request just to retrieve this info, it will slow down the interface and it's just a few bytes, we can have it already there to use.

**Comment by facundobatista** [comment]
This is already done
