### ISSUE TITLE
graph appears out of place on a 11" laptop

### ISSUE THREAD

**Issue by fbrau** [facundobatista/kilink#98]
on firefox (default zoom)
desktop DPI 102, btw

snapshot
![captura de pantalla_2016-01-22_08-40-02](https://cloud.githubusercontent.com/assets/8375315/12509863/8a852476-c0fd-11e5-9971-05a59ebaeb71.png)

**Comment by facundobatista** [comment]
Yes, the tree placement is a mess right now; IIUC @matibarriento is working on that or will work very soon now

**Comment by matibarriento** [comment]
Fixed. It was some css class. Deploy is coming

**Comment by fbrau** [comment]
now it is in its place (looks good)

<a href="http://i.imgur.com/jFVXVdd.png">
  <img src="http://imgur.com/jFVXVddl.png" />
</a>

**Comment by facundobatista** [comment]
Much better in current UI
