### ISSUE TITLE
Turn the edition process of a single kilink into a single-page

### ISSUE THREAD

**Issue by pablocelayes** [facundobatista/kilink#99]
Currently, a new URL is generated and a server-side HTML page is served for each version of a kilink that is created. This generates excessive and redundant requests and also code repetition between API and web app.

We propose to have a single URL for each kilink, and use a fragment identifier (#) to refer to the different versions of it.

e.g.:
http://linkode.org/ruPDWWYSKrKOiP5o4zwS91#1
http://linkode.org/ruPDWWYSKrKOiP5o4zwS91#2

**Comment by facundobatista** [comment]
This is part of the migration to "have a very simple web app served by the API"

**Comment by StyXman** [comment]
But *please* leave a mobile version that does not (ab)use JS...
